# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [1]:
import numpy as np


arr = np.random.uniform(low=0, high=20, size=(4, 7))
arr_min = np.min(arr)
arr_max = np.max(arr)

a = 1 / (arr_max - arr_min)
b = -arr_min / (arr_max - arr_min)
arr_norm = a * arr + b

print("Исходный массив:\n", arr)
print("Нормализованный массив:\n", arr_norm)

Исходный массив:
 [[ 0.78373443 18.82905465 16.52707892 10.26225706 12.51321603  5.00496866
  15.28927375]
 [ 9.06989631 16.33755103  0.63106311 12.4455526  10.33521397 12.83800543
   4.75790617]
 [17.23361458  3.3850382  11.34860163  7.13431065  3.73156614  3.90954804
   9.70750113]
 [ 2.56756275 19.30124094 14.20459567  1.55433203 19.00721553  6.15012446
  18.7829434 ]]
Нормализованный массив:
 [[0.00817728 0.97470906 0.85141213 0.51585979 0.6364242  0.2342723
  0.78511361]
 [0.45199533 0.84126076 0.         0.63280005 0.51976746 0.65382036
  0.2210393 ]
 [0.88925513 0.14750663 0.57404587 0.34832274 0.16606714 0.17560009
  0.48614631]
 [0.10372154 1.         0.72701678 0.04945153 0.9842516  0.2956084
  0.97223928]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [6]:
matrix = np.random.randint(0, 11, size=(8, 10))

min_index = np.argmin(np.sum(matrix, axis=1))
print(matrix,"\n")
print("Строка с минимальной суммой значений:")
print(matrix[min_index])

[[ 6  0  3  1  4  7  0  0  2  5]
 [ 0  7  1  0  2  1  7  7  0  3]
 [10  8  2  1  6  2  4  0  9  1]
 [ 9  8  4  9  9  6  3  3  4  7]
 [10  1  4  2  4  4  4  3  8  1]
 [ 6  6 10  6  8  2  9  6  8  4]
 [ 3  7  6  7  3  5  8  4  2  9]
 [ 2  7  9  4  3 10  1  6  1  1]] 

Строка с минимальной суммой значений:
[6 0 3 1 4 7 0 0 2 5]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [7]:
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])

distance = np.linalg.norm(vec1 - vec2)
print(distance)

5.196152422706632


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [8]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

X = -np.linalg.inv(A).dot(C).dot(np.linalg.inv(B))

print(X)

[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [21]:
lst = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=np.int32,skiprows=1)
lst[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [22]:
for column in range(1,3): 
  print(f'среднее значение: {np.mean(lst[:, column])}', f'минимум: {np.min(lst[:, column])}', f'максимум: {np.max(lst[:, column])}', f'медиана: {np.median(lst[:, column])}', sep='\n', end='\n\n')

среднее значение: 21601.00169
минимум: 0
максимум: 2147483647
медиана: 40.0

среднее значение: 9.05528
минимум: 1
максимум: 39
медиана: 9.0



3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [25]:
qua = np.quantile(lst[:,1], 0.75)
o = lst[:,1] <= qua
lst[o]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [ 43407,     35,      7],
       [498432,     65,     15],
       [370915,      5,      4]], dtype=int32)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [26]:
num_times = np.sum(lst[:, 1] == 0)
print("Количество рецептов со временем выполнения, равным 0: ", num_times)
lst[:, 1] = np.where(lst[:, 1] == 0, 1, lst[:, 1])


Количество рецептов со временем выполнения, равным 0:  479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [29]:
uni = np.unique(lst[:, 1:], axis=0).shape[0]
print(uni)

4183


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [31]:
uni = np.unique(lst[:, 2])
col_uni = uni.shape[0]
print('Кол-во:', col_uni, 'Какие:', uni, sep='\n')

Кол-во:
37
Какие:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [33]:
ingredients = lst[lst[:, 2] <= 5]
ingredients

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [34]:
ingredients = lst[:, 2] / lst[:, 1]
print(ingredients)

max_ingredients = np.max(ingredients)
print(max_ingredients)

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [36]:
top = lst[lst[:, 1].argsort()[::-1]][:100]
print(top[:,1].mean())

21518445.39


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [37]:
randd = lst[np.random.randint(lst.shape[0], size=10)]
print(randd)

[[ 93543      6      5]
 [114174     20      8]
 [104215     50     11]
 [346599     25      6]
 [295273     15      5]
 [ 40056    190      9]
 [ 71535     75      5]
 [223584     25      8]
 [ 51784     15     12]
 [107404    120     22]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [38]:
less = lst[lst[:, 2] < np.mean(lst[:, 2])]
p_less = len(less) / len(lst) * 100
print(p_less)

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [40]:
simple = lst.copy()
mm = (lst[:, 1] <= 20) & (lst[:, 2] <= 5)
new = mm.astype(int)
simple = np.column_stack([simple, new])
simple

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [41]:
pe = simple[:,3] == 1
count = np.count_nonzero(pe)
print(count / simple.shape[0] *100, '%')

9.552 %


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [46]:
short = lst[lst[:,1] < 10]
mm = (lst[:,1] >= 10) & (lst[:,1] < 20)
original = lst[mm]
long = lst[lst[:,1] >= 20]
minimal = min(short.shape[0], original.shape[0], long.shape[0])
result = np.array([short[:minimal], original[:minimal], long[:minimal]])
result

array([[[ 67660,      5,      6],
        [366174,      7,      9],
        [204134,      5,      3],
        ...,
        [420725,      5,      3],
        [  4747,      1,      9],
        [370915,      5,      4]],

       [[ 94746,     10,      6],
        [ 33941,     18,      9],
        [446597,     15,      5],
        ...,
        [  9831,     15,      7],
        [335859,     12,     14],
        [256812,     10,      3]],

       [[127244,     60,     16],
        [ 23891,     25,      7],
        [157911,     60,     14],
        ...,
        [168901,     25,      7],
        [392339,     35,     13],
        [206732,     45,     10]]], dtype=int32)